### ISSUE TITLE
is project alive?

### ISSUE THREAD

**Issue by andyglow** [spotify/dataenum#37]

**Comment by pettermahlen** [comment]
Yes, but we're not making a lot of active changes to it. It's been mostly used in Android projects, and there are very few remaining usages since we've been moving to Kotlin and sealed classes instead.

**Comment by andyglow** [comment]
I see.
But still, would you be open to accept couple of PRs?

- I am looking for the way to make sure that adt members are Serializable. Or more generally speaking I'd like to be able to instruct the spec with all the `interfaces` that need to be implemented by members. Basically need to copy them exactly the same way you copy type parameters.
```
@DataEnum
public interface Expr_dataenum extends Serializable {
  dataenum_case Lit(int i);
  dataenum_case Sum(Expr_dataenum l, Expr_dataenum r);
  dataenum_case Mul(Expr_dataenum l, Expr_dataenum r);
}
```
- and another one. allow default methods on spec interface which won't affect the `values`, but instead would be just copied to the base adt class
```
@DataEnum
public interface Expr_dataenum extends Serializable {
  dataenum_case Lit(int value);
  dataenum_case Sum(Expr_dataenum l, Expr_dataenum r);
  dataenum_case Mul(Expr_dataenum l, Expr_dataenum r);

  default int eval(Expr expr) {
    return expr.map(
      lit -> lit.value(),
      sum -> eval(sum.l()) + eval(sum.r()),
      mul -> eval(mul.l()) * eval(mul.r()),
    );
  }
}
```
what do you think?

**Comment by andyglow** [comment]
@pettermahlen please check if [this](https://github.com/spotify/dataenum/pull/38) is something that can be considered a candidate to merge
